//TASKS
export const TASKS_FETCHED_BY_PAGE = 'TASKS_FETCHED_BY_PAGE';
export const NEW_TASK_CREATED = 'NEW_TASK_CREATED';
export const TASK_UPDATED = 'TASK_UPDATED';
export const TASK_DELETED = 'TASK_DELETED';

